[package]
name = "mysomeid"
version = "0.1.0"
edition = "2021"
description = "my social media id"

[features]
default = ["std"]
std = ["concordium-std/std", "concordium-cis2/std"]

[dependencies]
concordium-std = "5.0.0"
concordium-cis2 = "2.0.0"
hex = "0.4"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
opt-level = "s"
