# docker-compose.yml
services:
  scraper:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000" # The gateway
      - "5901:5901"
    environment:
      NODE_ENV: production
      HEADLESS: 1
  scraper-dev:
    build:
      dockerfile: ./Dockerfile-dev
    ports:
      - "3000:3000" # The gateway
      - "5901:5901"
    environment:
      HEADLESS: 0
    volumes:
      - ./user-data:/app/scraper/user-data
      - ./test-data:/app/scraper/test-data
